# This file contains values from Cookiecutter

default_context:
  project_name: "auto_pytest_mg"
  project_description: "Awesome `auto_pytest_mg` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "auto_pytest_mg"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "auto_pytest_mg"
  email: "ryan.ozelie@gmail.com"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "cli"
